# Generated by Django 4.0.3 on 2024-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_id_alter_progress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='video_link',
            field=models.TextField(blank=True, help_text='Youtube Link', null=True, verbose_name='Link'),
        ),
    ]
