# Generated by Django 4.0.3 on 2024-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitting',
            options={'ordering': ['-end'], 'permissions': (('view_sittings', 'Can see completed exams.'),)},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video_link',
            field=models.FileField(blank=True, help_text='Upload your PowerPoint Presentation', null=True, upload_to='pptx_files/', verbose_name='PowerPoint pptx'),
        ),
    ]
