# Generated by Django 4.0.3 on 2024-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_sitting_options_alter_quiz_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='video_link',
        ),
        migrations.AddField(
            model_name='quiz',
            name='slides',
            field=models.TextField(blank=True, help_text='Copy the link Embed Link', null=True, verbose_name='ppt link'),
        ),
    ]
