# Generated by Django 4.2.4 on 2024-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_sitting_user_attempt_alter_quiz_slides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='current_score',
            field=models.IntegerField(default=1, verbose_name='Current Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_attempt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attempt'),
        ),
    ]
