# Generated by Django 4.2.4 on 2024-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_sitting_current_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='user_attempt',
            field=models.IntegerField(default=0, verbose_name='Attempt'),
        ),
    ]
