# Generated by Django 4.2.4 on 2024-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_sitting_user_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='user_passed',
            field=models.BooleanField(default=False, verbose_name='Passed?'),
        ),
    ]
